import { useEffect, useState } from 'react'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import ScriptDisplay from '@/components/ScriptDisplay'
import { Button } from '@/components/ui/button'
import { ArrowRight } from 'lucide-react'
import { useNavigate } from 'react-router-dom'

import { scriptProjects } from '../lib/projectData'

// Sample scripts for demonstration
const exampleScripts = [
  {
    id: 'action-heist',
    title: 'The Ultimate Heist',
    genre: 'action',
    synopsis:
      "A skilled ex-thief is pulled back into the game for one final score - breaking into the world's most secure vault.",
  },
  {
    id: 'drama-reunion',
    title: 'The Reunion',
    genre: 'drama',
    synopsis:
      'After thirty years of estrangement, two sisters reunite at their childhood home to confront the painful truth about the night that tore their family apart.',
  },
  {
    id: 'comedy-mixup',
    title: 'The Wedding Mix-Up',
    genre: 'comedy',
    synopsis:
      'When a wedding planner accidentally double-books two weddings at the same venue on the same day, chaos ensues as she desperately tries to keep both ceremonies on track.',
  },
]

const Examples = () => {
  const [activeTab, setActiveTab] = useState('action-heist')
  const navigate = useNavigate()

  const activeScript = exampleScripts.find((script) => script.id === activeTab)

  const [fileContent, setFileContent] = useState('')

  useEffect(() => {
    fetch('/script-text.txt')
      .then((response) => response.text())
      .then((text) => setFileContent(text))
      .catch((error) => console.error('Error loading file:', error))
  }, [])

  return (
    <div className="min-h-screen bg-background text-foreground">
      <Header />
      <main className="py-20 pt-32">
        <div className="container mx-auto px-4 md:px-6">
          <div className="min-w-4xl mx-auto">
            <div className="text-center mb-12">
              <h1 className="font-display text-4xl font-medium mb-4 mt-12">
                Example Scripts
              </h1>
              <p className="text-muted-foreground text-lg max-w-2xl mx-auto">
                Browse through these sample scripts generated by our AI to see
                the quality and variety of screenplays CinematicScribe can
                create.
              </p>
            </div>

            <Tabs
              value={activeTab}
              onValueChange={setActiveTab}
              className="mb-12"
              style={{
                maxWidth: '100%',
                display: 'flex',
                justifyContent: 'center',
              }}
            >
              <TabsList className="flex max-w-4xl flex-1">
                <TabsTrigger value="action-heist" className="flex-1">
                  Action
                </TabsTrigger>
                <TabsTrigger value="drama-reunion" className="flex-1">
                  Drama
                </TabsTrigger>
                <TabsTrigger value="comedy-mixup" className="flex-1">
                  Comedy
                </TabsTrigger>
              </TabsList>
            </Tabs>

            <div className="mt-8 flex justify-center">
              {activeScript && (
                <ScriptDisplay
                  title={activeScript.title}
                  synopsis={activeScript.synopsis}
                  script={fileContent}
                />
              )}
            </div>

            <div className="text-center mt-16">
              <p className="text-lg mb-6">
                Ready to create your own professional screenplay?
              </p>
              <Button
                size="lg"
                onClick={() => navigate('/create')}
                className="group"
              >
                Start Writing Your Script
                <ArrowRight className="ml-2 h-4 w-4 transition-transform group-hover:translate-x-1" />
              </Button>
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  )
}

export default Examples
